### ISSUE TITLE
Wrong SignInScheme for External identity providers in Quickstarts

### ISSUE THREAD

**Issue by vodesoft** [IdentityServer/IdentityServer4.Samples#215]
Hello,

I have tried to use external provider login in Combined_AspNetIdentity_and_EntityFrameworkStorage project. I found that the _signInManager.GetExternalLoginInfoAsync(); returns null in ExternalLoginCallback. As result the user is redirected back to Login page. 

The reason is in the wrong SignInScheme configuration in Startup.cs for Google and oidc registrations used in quick starts:
`.AddGoogle("Google", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;`

Please consider to update sources with something like: 
`.AddGoogle("Google", options =>
                {
                    options.SignInScheme = IdentityConstants.ExternalScheme;`

Thanks

**Comment by brockallen** [comment]
Good catch. I didn't accommodate for ASP.NET Identity's taking over the external cookie in that sample. Thanks.

**Comment by brockallen** [comment]
Fixed, thanks.

**Comment by smoses2** [comment]
Thanks @vodesoft.   
Your suggestion saved me time and frustration:
.AddGoogle("Google", options => { options.SignInScheme = IdentityConstants.ExternalScheme;

I was working with Quickstart 6 and had modified the external provider flow to use the new registration page as Kevin Docx describes [on Pluralsight](https://app.pluralsight.com/player?course=asp-dotnet-core-oauth2-openid-connect-securing&author=kevin-dockx&name=asp-dotnet-core-oauth2-openid-connect-securing-m10&clip=4&mode=live).  I really like this workflow - consider this for the quickstart.

When the user returned to ExternalLoginCallback, and called:
var info = await _signInManager.GetExternalLoginInfoAsync()

info turned out to be null.  This was corrected with your fix.

@brockallen - could this .AddGoogle option modification also be added to Quickstart 6 Startup?
I looked in Quickstart 7 idserver startup, but also did not see it there.
