### ISSUE TITLE
Using indetityServer

### ISSUE THREAD

**Issue by walid1001** [IdentityServer/IdentityServer4.Samples#29]
Hi,

I would like to use identity server as an openid authentication server repository for an API I'm building 
is there a clear example with a user db as an example ?

regards,

**Comment by PivotalAnimal** [comment]
I don't want to step on anyones toes, but my project is aiming to do precisely that. It is not very far along yet, but you can run the EF Update-Database command to see for yourself a generated db schema. I am working on seeding the DB with some garbage data so that I can run the IS4 examples pretty much as is. Adding the bearer token package and an ancillary website that relies on IS4 is a next step as well. See: https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore

**Comment by brockallen** [comment]
We have quickstarts: https://identityserver4.readthedocs.io/en/release/quickstarts/0_overview.html
